config/routes.rb
Rails.application.routes.draw do
  resources :memos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'memos#index'

  # get '/mockServiceWorker.js', to: 'memos_controller#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/memo.rb
class Memo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: %i[ show edit update destroy ]

  # GET /memos or /memos.json
  def index
    @memos = Memo.all
  end

  # GET /memos/1 or /memos/1.json
  def show
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos or /memos.json
  def create
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        format.html { redirect_to memo_url(@memo), notice: "Memo was successfully created." }
        format.json { render :show, status: :created, location: @memo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1 or /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to memo_url(@memo), notice: "Memo was successfully updated." }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1 or /memos/1.json
  def destroy
    @memo.destroy

    respond_to do |format|
      format.html { redirect_to memos_url, notice: "Memo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      @memo = Memo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def memo_params
      params.require(:memo).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeployRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/_form.html.erb
<%= form_with(model: memo) do |form| %>
  <% if memo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
        <% memo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/memos/_memo.html.erb
<div id="<%= dom_id memo %>">
  <p>
    <strong>Title:</strong>
    <%= memo.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= memo.content %>
  </p>

</div>

app/views/memos/edit.html.erb
<h1>Editing memo</h1>

<%= render "form", memo: @memo %>

<br>

<div>
  <%= link_to "Show this memo", @memo %> |
  <%= link_to "Back to memos", memos_path %>
</div>

app/views/memos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Memos</h1>

<div id="memos">
  <% @memos.each do |memo| %>
    <%= render memo %>
    <p>
      <%= link_to "Show this memo", memo %>
    </p>
  <% end %>
</div>

<%= link_to "New memo", new_memo_path %>

app/views/memos/new.html.erb
<h1>New memo</h1>

<%= render "form", memo: @memo %>

<br>

<div>
  <%= link_to "Back to memos", memos_path %>
</div>

app/views/memos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @memo %>

<div>
  <%= link_to "Edit this memo", edit_memo_path(@memo) %> |
  <%= link_to "Back to memos", memos_path %>

  <%= button_to "Destroy this memo", @memo, method: :delete %>
</div>